org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=1.21.11
yarn_mappings=1.21.11+build.5
loader_version=0.19.2
loom_version=1.16-SNAPSHOT

mod_version=0.13.52
moulconfig_version=4.6.0
kotlin_version=2.1.10
maven_group=net.emutils

fabric_api_version=0.141.4+1.21.11
emhelpers_version=0.1.4
