package net.emutils.client.versioned;

import java.util.Map;
import org.jspecify.annotations.Nullable;

/**
 * Key names for the GLFW key codes that Minecraft 26.2 and earlier stored as {@code KEYSYM} keys.
 * 26.3 identifies keyboard keys by SDL scancode instead, so combos saved on older versions are
 * converted through the version-independent key name. Generated from 26.2's key table; F25 is
 * left out because 26.3 has no such key.
 */
final class LegacyGlfwKeys {
	private static final Map<Integer, String> NAMES = Map.ofEntries(
		Map.entry(32, "key.keyboard.space"),
		Map.entry(39, "key.keyboard.apostrophe"),
		Map.entry(44, "key.keyboard.comma"),
		Map.entry(45, "key.keyboard.minus"),
		Map.entry(46, "key.keyboard.period"),
		Map.entry(47, "key.keyboard.slash"),
		Map.entry(48, "key.keyboard.0"),
		Map.entry(49, "key.keyboard.1"),
		Map.entry(50, "key.keyboard.2"),
		Map.entry(51, "key.keyboard.3"),
		Map.entry(52, "key.keyboard.4"),
		Map.entry(53, "key.keyboard.5"),
		Map.entry(54, "key.keyboard.6"),
		Map.entry(55, "key.keyboard.7"),
		Map.entry(56, "key.keyboard.8"),
		Map.entry(57, "key.keyboard.9"),
		Map.entry(59, "key.keyboard.semicolon"),
		Map.entry(61, "key.keyboard.equal"),
		Map.entry(65, "key.keyboard.a"),
		Map.entry(66, "key.keyboard.b"),
		Map.entry(67, "key.keyboard.c"),
		Map.entry(68, "key.keyboard.d"),
		Map.entry(69, "key.keyboard.e"),
		Map.entry(70, "key.keyboard.f"),
		Map.entry(71, "key.keyboard.g"),
		Map.entry(72, "key.keyboard.h"),
		Map.entry(73, "key.keyboard.i"),
		Map.entry(74, "key.keyboard.j"),
		Map.entry(75, "key.keyboard.k"),
		Map.entry(76, "key.keyboard.l"),
		Map.entry(77, "key.keyboard.m"),
		Map.entry(78, "key.keyboard.n"),
		Map.entry(79, "key.keyboard.o"),
		Map.entry(80, "key.keyboard.p"),
		Map.entry(81, "key.keyboard.q"),
		Map.entry(82, "key.keyboard.r"),
		Map.entry(83, "key.keyboard.s"),
		Map.entry(84, "key.keyboard.t"),
		Map.entry(85, "key.keyboard.u"),
		Map.entry(86, "key.keyboard.v"),
		Map.entry(87, "key.keyboard.w"),
		Map.entry(88, "key.keyboard.x"),
		Map.entry(89, "key.keyboard.y"),
		Map.entry(90, "key.keyboard.z"),
		Map.entry(91, "key.keyboard.left.bracket"),
		Map.entry(92, "key.keyboard.backslash"),
		Map.entry(93, "key.keyboard.right.bracket"),
		Map.entry(96, "key.keyboard.grave.accent"),
		Map.entry(161, "key.keyboard.world.1"),
		Map.entry(162, "key.keyboard.world.2"),
		Map.entry(256, "key.keyboard.escape"),
		Map.entry(257, "key.keyboard.enter"),
		Map.entry(258, "key.keyboard.tab"),
		Map.entry(259, "key.keyboard.backspace"),
		Map.entry(260, "key.keyboard.insert"),
		Map.entry(261, "key.keyboard.delete"),
		Map.entry(262, "key.keyboard.right"),
		Map.entry(263, "key.keyboard.left"),
		Map.entry(264, "key.keyboard.down"),
		Map.entry(265, "key.keyboard.up"),
		Map.entry(266, "key.keyboard.page.up"),
		Map.entry(267, "key.keyboard.page.down"),
		Map.entry(268, "key.keyboard.home"),
		Map.entry(269, "key.keyboard.end"),
		Map.entry(280, "key.keyboard.caps.lock"),
		Map.entry(281, "key.keyboard.scroll.lock"),
		Map.entry(282, "key.keyboard.num.lock"),
		Map.entry(283, "key.keyboard.print.screen"),
		Map.entry(284, "key.keyboard.pause"),
		Map.entry(290, "key.keyboard.f1"),
		Map.entry(291, "key.keyboard.f2"),
		Map.entry(292, "key.keyboard.f3"),
		Map.entry(293, "key.keyboard.f4"),
		Map.entry(294, "key.keyboard.f5"),
		Map.entry(295, "key.keyboard.f6"),
		Map.entry(296, "key.keyboard.f7"),
		Map.entry(297, "key.keyboard.f8"),
		Map.entry(298, "key.keyboard.f9"),
		Map.entry(299, "key.keyboard.f10"),
		Map.entry(300, "key.keyboard.f11"),
		Map.entry(301, "key.keyboard.f12"),
		Map.entry(302, "key.keyboard.f13"),
		Map.entry(303, "key.keyboard.f14"),
		Map.entry(304, "key.keyboard.f15"),
		Map.entry(305, "key.keyboard.f16"),
		Map.entry(306, "key.keyboard.f17"),
		Map.entry(307, "key.keyboard.f18"),
		Map.entry(308, "key.keyboard.f19"),
		Map.entry(309, "key.keyboard.f20"),
		Map.entry(310, "key.keyboard.f21"),
		Map.entry(311, "key.keyboard.f22"),
		Map.entry(312, "key.keyboard.f23"),
		Map.entry(313, "key.keyboard.f24"),
		Map.entry(320, "key.keyboard.keypad.0"),
		Map.entry(321, "key.keyboard.keypad.1"),
		Map.entry(322, "key.keyboard.keypad.2"),
		Map.entry(323, "key.keyboard.keypad.3"),
		Map.entry(324, "key.keyboard.keypad.4"),
		Map.entry(325, "key.keyboard.keypad.5"),
		Map.entry(326, "key.keyboard.keypad.6"),
		Map.entry(327, "key.keyboard.keypad.7"),
		Map.entry(328, "key.keyboard.keypad.8"),
		Map.entry(329, "key.keyboard.keypad.9"),
		Map.entry(330, "key.keyboard.keypad.decimal"),
		Map.entry(331, "key.keyboard.keypad.divide"),
		Map.entry(332, "key.keyboard.keypad.multiply"),
		Map.entry(333, "key.keyboard.keypad.subtract"),
		Map.entry(334, "key.keyboard.keypad.add"),
		Map.entry(335, "key.keyboard.keypad.enter"),
		Map.entry(336, "key.keyboard.keypad.equal"),
		Map.entry(340, "key.keyboard.left.shift"),
		Map.entry(341, "key.keyboard.left.control"),
		Map.entry(342, "key.keyboard.left.alt"),
		Map.entry(343, "key.keyboard.left.win"),
		Map.entry(344, "key.keyboard.right.shift"),
		Map.entry(345, "key.keyboard.right.control"),
		Map.entry(346, "key.keyboard.right.alt"),
		Map.entry(347, "key.keyboard.right.win"),
		Map.entry(348, "key.keyboard.menu")
	);

	private LegacyGlfwKeys() {
	}

	static @Nullable String name(int glfwKeyCode) {
		return NAMES.get(glfwKeyCode);
	}
}
